### PR TITLE
Added some plotting functionality

### PR DESCRIPTION
**Pull request by LouisK130**
Added _features.csv contents as axis options
Added offset option so log plots work
Added navigation and zooming to plot
Change jQuery to 1.9.1 instead of 1.5.1 (Navigation depended on it, not sure if a problem)

### CODE REVIEW

**Comment by joefutrelle** [comment]
Very cool.

There's a potential problem, however. I can't seem to drag-select groups of points anymore, because clicking and dragging now translates the axes. Is there a way to get out of that mode so drag-selection still works, or does that need to be added?

**Comment by LouisK130** [comment]
Hold control while you drag to select instead of pan.

Also forgot to mention that this version limits selection to 50 at a time, in hopes to fix the issue where accidentally selecting too many could cause a crash. That number may need to be adjusted, I just made it up.

**Comment by joefutrelle** [comment]
Thanks. I'm going to open a few issues, have a look.

**Comment by joefutrelle** [comment]
Not sure where to open those issues, so I'll list them here.

* There are still harcoded "localhost" URLs; these should be reverted and you should configure DASHBOARD_BASE_URL in dashboard.wsgi instead, to get the correct behavior
* Ctrl-drag does not seem to work on Mac; I will test on Windows but Ctrl-dragging was not working via remote desktop to a Windows box from a Mac--I think that's the same Mac issue.

**Comment by LouisK130** [comment]
Okay, I pulled that configuration change, but I'm not sure what hardcoded URLs you're referring to. A quick search of "localhost" in the project only turns up some references from files I didn't change. I'm pretty sure I removed all mine before committing.

I changed the modifier key to shift instead of control. I have a Mac to test on, but unfortunately not an Apple keyboard. Shift worked using the normal keyboard and Mac, but that should be tested.

**Comment by joefutrelle** [comment]
OK, will pull and then test the Mac keyboard. The reason I jumped to the conclusion that there were hardcoded localhost URLs is that I was getting broken images back when I selected points on a chart--I will try to reproduce and gather more information about what the URLs of those broken images are.

**Comment by joefutrelle** [comment]
Unable to reproduce the broken image link issue, so forget my erroneous conclusion.

Shift-drag works on a Mac and Windows.

**Pull request merged**
