### PR TITLE
Fixed an issue with selecting points on scatter plots

### PR DESCRIPTION
**Pull request by LouisK130**

### CODE REVIEW

**Comment by joefutrelle** [comment]
I'm reviewing this now. How do I reproduce the problem behavior and the fixed behavior, so I can compare?

**Comment by hsosik** [comment]
I believe you can see the problem by changing to log scaling on a plot and then using the mouse to draw a box around selected points to display the corresponding ROIs. If you experiment, you will confirm that the displayed box coordinates and the selected points are not properly matched.

**Comment by joefutrelle** [comment]
Does that mean if you select points on the log plot you'll get different ROIs than if you select the same points on the linear plot? I'm not seeing that problem on the MVCO dashboard, so I must not be doing the right thing to trigger the bug.

**Comment by LouisK130** [comment]
Switching graph type from log to linear never caused an issue. The problem was just with applying constant offsets to either axis. If you add an offset, then try to select some points, you'll notice that the selection corresponds to the orignal set of points.

**Comment by joefutrelle** [comment]
OK, I was able to reproduce the behavior on the MVCO dashboard, and the fix on a fresh install from @LouisK130's mod appears to work.

What I saw is that if I select a group of points and note which ROIs are displayed, then apply an axis offset and select the same points, a different set of ROIs is displayed. No such issue with the fixed code.

**Pull request merged**
